name = "eurydice-discord-bot"
main = "./src/server.ts"
compatibility_date="2022-02-26"

account_id = "352f8084962a33cd92ca448b5aec6d5e"
workers_dev = true

[[rules]]
type = "ESModule"
globs = [ "**/*.ts" ]

[env.dev]

[env.production]

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
# DISCORD_TEST_GUILD_ID
